packages:
  - apps/*
  - apps/examples/*
  - packages/*
  - packages/@*/*

catalog:
  "@remotion/animated-emoji": 4.0.429
  "@remotion/animation-utils": 4.0.429
  "@remotion/bundler": 4.0.429
  "@remotion/captions": 4.0.429
  "@remotion/cli": 4.0.429
  "@remotion/cloudrun": 4.0.429
  "@remotion/enable-scss": 4.0.429
  "@remotion/eslint-config": 4.0.429
  "@remotion/eslint-plugin": 4.0.429
  "@remotion/fonts": 4.0.429
  "@remotion/gif": 4.0.429
  "@remotion/google-fonts": 4.0.429
  "@remotion/install-whisper-cpp": 4.0.429
  "@remotion/lambda": 4.0.429
  "@remotion/layout-utils": 4.0.429
  "@remotion/licensing": 4.0.429
  "@remotion/lottie": 4.0.429
  "@remotion/media": 4.0.429
  "@remotion/media-parser": 4.0.429
  "@remotion/media-utils": 4.0.429
  "@remotion/motion-blur": 4.0.429
  "@remotion/noise": 4.0.429
  "@remotion/openai-whisper": 4.0.429
  "@remotion/paths": 4.0.429
  "@remotion/player": 4.0.429
  "@remotion/preload": 4.0.429
  "@remotion/renderer": 4.0.429
  "@remotion/rive": 4.0.429
  "@remotion/shapes": 4.0.429
  "@remotion/skia": 4.0.429
  "@remotion/studio": 4.0.429
  "@remotion/tailwind": 4.0.429
  "@remotion/tailwind-v4": 4.0.429
  "@remotion/three": 4.0.429
  "@remotion/transitions": 4.0.429
  "@remotion/webcodecs": 4.0.429
  "@remotion/whisper-web": 4.0.429
  "@remotion/zod-types": 4.0.429
  "@tailwindcss/postcss": ^4.1.1
  "@types/node": ^24.5.2
  "@types/react": ^18.3.0
  "@types/react-dom": ^18.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.8.0
  next: ^15.0.0
  prettier: ^3.3.3
  react: ^18.3.1
  react-dom: ^18.3.1
  remotion: 4.0.429
  tailwind-merge: ^2.5.5
  tailwindcss: ^4.1.1
  tsx: ^4.16.2
  typescript: ^5.6.3
  zod: ^4.3.6
  zustand: ^5.0.8

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sharp

strictDepBuilds: true
