import { baseTokens, rel, type BaseTokens } from "./tokens";

export const modernLegacyTokens: BaseTokens = {
  ...baseTokens,
  palette: {
    ...baseTokens.palette,
    canvas: "#F3EEE2",
    canvasShade: "#DDD6CA",
    smoke: "#D8D2C7",
    ivory: "#F7F3EA",
    gold: "#B49B63",
    rule: "rgba(180, 155, 99, 0.78)",
    deepGreen: "#203229",
    deepGreenWash: "rgba(32, 50, 41, 0.16)",
    ink: "#211C17",
    textSecondary: "rgba(33, 28, 23, 0.76)",
    textMeta: "rgba(33, 28, 23, 0.58)",
    panelFill: "rgba(247, 243, 234, 0.62)",
    panelStroke: "rgba(180, 155, 99, 0.32)",
  },
  safeArea: {
    x: rel("width", 0.0833),
    y: rel("height", 0.0889),
  },
  layout: {
    ...baseTokens.layout,
    contentMaxWidth: rel("width", 0.6667),
    panelWidth: rel("width", 0.6146),
    panelMinHeight: rel("height", 0.3963),
    panelPaddingX: rel("width", 0.0479),
    panelPaddingTop: rel("min", 0.05),
    panelPaddingBottom: rel("min", 0.0593),
    alignmentShiftLower: rel("min", 0.0519),
    alignmentShiftCenter: rel("height", 0),
    ruleWidth: rel("width", 0.3958),
    ruleGap: rel("min", 0.0056, { minPx: 4 }),
    hairline: rel("min", 1 / 1080, {
      minPx: 1,
      maxPx: 2,
      round: "int",
    }),
    innerFrameInset: rel("min", 12 / 1080, {
      minPx: 8,
      round: "int",
    }),
    maxSubtitleWidth: rel("width", 0.5104),
  },
  typography: {
    ...baseTokens.typography,
    eyebrow: {
      ...baseTokens.typography.eyebrow,
      fontSize: rel("min", 0.0167),
      letterSpacing: "0.28em",
    },
    title: {
      ...baseTokens.typography.title,
      fontSize: rel("min", 0.1222),
      minFontSize: rel("min", 0.1037),
      letterSpacing: "0.08em",
      lineHeight: 0.92,
    },
    subtitle: {
      ...baseTokens.typography.subtitle,
      fontSize: rel("min", 0.0296),
      minFontSize: rel("min", 0.0241),
      letterSpacing: "0.032em",
      lineHeight: 1.28,
      maxWidth: rel("width", 0.5104),
    },
    meta: {
      ...baseTokens.typography.meta,
      fontSize: rel("min", 0.0148),
      letterSpacing: "0.24em",
    },
  },
  motion: {
    ...baseTokens.motion,
    backgroundStartOpacity: 0.86,
    panelRise: rel("min", 0.0167),
    titleRise: rel("min", 0.0222),
    subtitleRise: rel("min", 0.013),
    titleMaskOverflow: rel("min", 0.02),
  },
  imageTreatment: {
    ...baseTokens.imageTreatment,
    opacity: 0.36,
    grayscale: 1,
    saturation: 0.35,
    brightness: 0.95,
    washOpacity: 0.42,
    vignetteOpacity: 0.16,
  },
};
