import { auctionProgramThemes } from "../../designSystem/auctionThemeTokens";
import { baseTokens, rel, type BaseTokens } from "./tokens";

const modernLegacyTheme = auctionProgramThemes.modernLegacy;

export const modernLegacyTokens: BaseTokens = {
  ...baseTokens,
  palette: {
    ...baseTokens.palette,
    canvas: "#F3EEE2",
    canvasShade: "#DDD6CA",
    smoke: modernLegacyTheme.canvasSmoke,
    ivory: modernLegacyTheme.canvasIvory,
    gold: modernLegacyTheme.accentGold,
    rule: "rgba(180, 155, 99, 0.78)",
    deepGreen: modernLegacyTheme.deepTone,
    deepGreenWash: modernLegacyTheme.deepToneWash,
    ink: modernLegacyTheme.titleInk,
    textSecondary: "rgba(33, 28, 23, 0.76)",
    textMeta: "rgba(33, 28, 23, 0.58)",
    panelFill: "rgba(247, 243, 234, 0.62)",
    panelStroke: modernLegacyTheme.panelStroke,
  },
  safeArea: {
    x: rel("width", 0.0833),
    y: rel("height", 0.0889),
  },
  layout: {
    ...baseTokens.layout,
    contentMaxWidth: rel("width", 0.6667),
    panelWidth: rel("width", 0.6146),
    panelMinHeight: rel("height", 0.3963),
    panelPaddingX: rel("width", 0.0479),
    panelPaddingTop: rel("min", 0.05),
    panelPaddingBottom: rel("min", 0.0593),
    alignmentShiftLower: rel("min", 0.0519),
    alignmentShiftCenter: rel("height", 0),
    ruleWidth: rel("width", 0.3958),
    ruleGap: rel("min", 0.0056, { minPx: 4 }),
    hairline: rel("min", 1 / 1080, {
      minPx: 1,
      maxPx: 2,
      round: "int",
    }),
    innerFrameInset: rel("min", 12 / 1080, {
      minPx: 8,
      round: "int",
    }),
    maxSubtitleWidth: rel("width", 0.5104),
  },
  typography: {
    ...baseTokens.typography,
    eyebrow: {
      ...baseTokens.typography.eyebrow,
      fontSize: rel("min", 0.0167),
      letterSpacing: "0.28em",
    },
    title: {
      ...baseTokens.typography.title,
      fontSize: rel("min", 0.1222),
      minFontSize: rel("min", 0.1037),
      letterSpacing: "0.08em",
      lineHeight: 0.92,
    },
    subtitle: {
      ...baseTokens.typography.subtitle,
      fontSize: rel("min", 0.0296),
      minFontSize: rel("min", 0.0241),
      letterSpacing: "0.032em",
      lineHeight: 1.28,
      maxWidth: rel("width", 0.5104),
    },
    meta: {
      ...baseTokens.typography.meta,
      fontSize: rel("min", 0.0148),
      letterSpacing: "0.24em",
    },
  },
  motion: {
    ...baseTokens.motion,
    backgroundStartOpacity: 0.86,
    panelRise: rel("min", 0.0167),
    titleRise: rel("min", 0.0222),
    subtitleRise: rel("min", 0.013),
    titleMaskOverflow: rel("min", 0.02),
  },
  imageTreatment: {
    ...baseTokens.imageTreatment,
    opacity: 0.36,
    grayscale: 1,
    saturation: 0.35,
    brightness: 0.95,
    washOpacity: 0.42,
    vignetteOpacity: 0.16,
  },
  infoBoard: {
    ...baseTokens.infoBoard,
    panelWidth: rel("width", 0.786),
    panelMinHeight: rel("height", 0.338),
    panelPaddingX: rel("width", 0.0615),
    panelPaddingY: rel("min", 0.061),
    panelBiasInset: rel("width", 0.028),
    panelShiftY: rel("min", 0.038),
    maxPrimaryWidth: rel("width", 0.468),
    secondaryColumnWidth: rel("width", 0.222),
    columnGap: rel("width", 0.046),
    blockGap: rel("min", 0.032),
    lineGap: rel("min", 0.013),
    secondaryLineGap: rel("min", 0.0102),
    titleFontSize: rel("min", 0.084),
    titleMinFontSize: rel("min", 0.068),
    modeFontSize: rel("min", 0.0157),
    bodyFontSize: rel("min", 0.0231),
    venueFontSize: rel("min", 0.0185),
    noteFontSize: rel("min", 0.0168),
    softFieldWidth: rel("width", 0.742),
    softFieldHeight: rel("height", 0.286),
    fieldShiftY: rel("min", 0.015),
    lineDrawWidth: rel("width", 0.424),
    secondaryRuleWidth: rel("width", 0.24),
  },
};
