import { auctionProgramThemes } from "../../designSystem/auctionThemeTokens";
import { baseTokens, rel, type BaseTokens } from "./tokens";

const modernLegacyTheme = auctionProgramThemes.modernLegacy;

export const modernLegacyResolveTokens: BaseTokens = {
  ...baseTokens,
  palette: {
    ...baseTokens.palette,
    canvas: "#F3EEE2",
    canvasShade: "#DDD6CA",
    ivory: modernLegacyTheme.canvasIvory,
    paleSmoke: "#E1DBD0",
    smoke: modernLegacyTheme.canvasSmoke,
    mutedGold: modernLegacyTheme.accentGold,
    mutedGoldSoft: "rgba(180, 155, 99, 0.38)",
    deepGreen: modernLegacyTheme.deepTone,
    deepGreenWash: modernLegacyTheme.deepToneWash,
    ink: modernLegacyTheme.titleInk,
    textSecondary: "rgba(33, 28, 23, 0.74)",
    textMeta: "rgba(33, 28, 23, 0.56)",
    panelFill: "rgba(247, 243, 234, 0.74)",
    panelFillAlpha: "rgba(247, 243, 234, 0.18)",
    panelStroke: modernLegacyTheme.panelStroke,
    frameStroke: "rgba(180, 155, 99, 0.22)",
    scaffoldTone: "rgba(180, 155, 99, 0.5)",
  },
  layout: {
    ...baseTokens.layout,
    openingPanelWidth: rel("width", 0.6146),
    openingPanelMinHeight: rel("height", 0.3963),
    openingPanelPaddingX: rel("width", 0.0479),
    openingPanelPaddingTop: rel("min", 0.05),
    openingPanelPaddingBottom: rel("min", 0.0593),
    openingRuleWidth: rel("width", 0.3958),
    openingTitleWidth: rel("width", 0.52),
    openingSubtitleWidth: rel("width", 0.46),
    openingMetaWidth: rel("width", 0.4),
    infoPanelWidth: rel("width", 0.76),
    infoPanelMinHeight: rel("height", 0.346),
    infoPanelPaddingX: rel("width", 0.0485),
    infoPanelPaddingY: rel("min", 0.05),
    infoPrimaryWidth: rel("width", 0.4),
    infoSecondaryWidth: rel("width", 0.16),
    infoColumnGap: rel("width", 0.04),
    fieldWidth: rel("width", 0.73),
    fieldHeight: rel("height", 0.29),
    fieldTop: rel("height", 0.17),
    veilWidth: rel("width", 0.56),
    veilHeight: rel("height", 0.36),
    panelAlphaWidth: rel("width", 0.5),
    panelAlphaHeight: rel("height", 0.27),
    panelAlphaTop: rel("height", 0.49),
  },
  typography: {
    ...baseTokens.typography,
    title: {
      ...baseTokens.typography.title,
      fontSize: rel("min", 0.1222),
      minFontSize: rel("min", 0.098),
      letterSpacing: "0.08em",
      lineHeight: 0.92,
    },
    subtitle: {
      ...baseTokens.typography.subtitle,
      fontSize: rel("min", 0.0296),
      minFontSize: rel("min", 0.0235),
      letterSpacing: "0.03em",
    },
    meta: {
      ...baseTokens.typography.meta,
      fontSize: rel("min", 0.0148),
    },
    label: {
      ...baseTokens.typography.label,
      fontSize: rel("min", 0.0145),
    },
  },
  motion: {
    ...baseTokens.motion,
    opening: {
      ...baseTokens.motion.opening,
      titleRise: rel("min", 0.0222),
      subtitleRise: rel("min", 0.013),
      metaRise: rel("min", 0.01),
      panelRise: rel("min", 0.0167),
    },
    text: {
      ...baseTokens.motion.text,
      rise: rel("min", 0.014),
      metaRise: rel("min", 0.01),
    },
    info: {
      ...baseTokens.motion.info,
      titleRise: rel("min", 0.015),
      bodyRise: rel("min", 0.011),
    },
    overlay: {
      ...baseTokens.motion.overlay,
      smallDrift: rel("min", 0.0055),
      mediumDrift: rel("min", 0.01),
    },
    backgroundLoop: {
      ...baseTokens.motion.backgroundLoop,
      veilOpacity: 0.17,
      fieldOpacity: 0.42,
      lineOpacity: 0.22,
    },
  },
};
